baseURL = "/"
languageCode = "en"
DefaultContentLanguage = "en"
title = "Website of Khanh Nguyen"
theme = "anatole"
summarylength = 10
enableEmoji = true

# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = "UA-123-45"

[params]
title = "Khanh Nguyen"
author = "Khanh Nguyen"
keywords = ""
favicon = "favicons/"
customCss = []
mainSections = ["post"]

## Math settings
[params.math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
[[params.socialIcons]]
icon = "fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/khanh-nguyen-4b1393b0/"

[[params.socialIcons]]
icon = "fa-github"
title = "GitHub"
url = "https://github.com/Kn99HN"

[[params.socialIcons]]
icon = "fa-envelope"
title = "e-mail"
url = "mailto:khanhnguyen99hn@gmail.com"

## Menu items

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"

  [[menu.main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/about/"

  [[menu.main]]
  name = "Resume"
  identifier = "resume"
  weight = 400
  url = "/resume/resume.pdf"